/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ImportRouteImport } from './routes/import'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiKeepAliveRouteImport } from './routes/api/keep-alive'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeepAliveRoute = ApiKeepAliveRouteImport.update({
  id: '/api/keep-alive',
  path: '/api/keep-alive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/bulk': typeof BulkRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/keep-alive': typeof ApiKeepAliveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/bulk': typeof BulkRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/keep-alive': typeof ApiKeepAliveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/bulk': typeof BulkRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/keep-alive': typeof ApiKeepAliveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/bulk'
    | '/export'
    | '/import'
    | '/sitemap.xml'
    | '/api/keep-alive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/bulk'
    | '/export'
    | '/import'
    | '/sitemap.xml'
    | '/api/keep-alive'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/bulk'
    | '/export'
    | '/import'
    | '/sitemap.xml'
    | '/api/keep-alive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  BulkRoute: typeof BulkRoute
  ExportRoute: typeof ExportRoute
  ImportRoute: typeof ImportRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiKeepAliveRoute: typeof ApiKeepAliveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keep-alive': {
      id: '/api/keep-alive'
      path: '/api/keep-alive'
      fullPath: '/api/keep-alive'
      preLoaderRoute: typeof ApiKeepAliveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  BulkRoute: BulkRoute,
  ExportRoute: ExportRoute,
  ImportRoute: ImportRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiKeepAliveRoute: ApiKeepAliveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
